language: go

dist: xenial

go_import_path: git.torproject.org/pluggable-transports/snowflake.git

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

go:
    - 1.10.x

env:
    - TRAVIS_NODE_VERSION="8" CC="gcc-5" CXX="g++-5"

before_install:
    - nvm install $TRAVIS_NODE_VERSION

install:
    - go get -u github.com/smartystreets/goconvey
    - go get -u github.com/keroserene/go-webrtc
    - go get -u github.com/pion/webrtc
    - go get -u github.com/dchest/uniuri
    - go get -u git.torproject.org/pluggable-transports/goptlib.git
    - go get -u git.torproject.org/pluggable-transports/websocket.git/websocket
    - go get -u google.golang.org/appengine
    - go get -u golang.org/x/crypto/acme/autocert
    - go get -u golang.org/x/net/http2
    - pushd proxy
    - npm install
    - popd

script:
    - test -z "$(go fmt ./...)"
    - go vet ./...
    - go test -v -race ./...
    - cd proxy
    - npm run lint
    - npm test
